### ISSUE TITLE
Test new core page block styles

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/papers#1]
See omeka/omeka-s#1480. Papers provides a few of its own custom block styles on top of the core styles. Test on `block-styles` branches of both Papers and Omeka S.

**Comment by mebrett** [comment]
As with CenterRow, the line at the top of the media embed blocks extends into the HTML block. When media size is "Large" there's not sufficient padding between the media and HTML
<img width="596" alt="Screen Shot 2020-01-06 at 4 22 03 PM" src="https://user-images.githubusercontent.com/2314070/71849757-d4202b00-30a0-11ea-8474-386cc5a372d0.png">

**Comment by mebrett** [comment]
Resolved with the fix on core.
