### ISSUE TITLE
Test new theme settings

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/papers#10]
This theme has some updates to the settings: 

* Users can now turn off background images. In "background layout", they can set it to "none" to turn off the default background image.
* If the user has turned off the background image, the theme will pick up the new setting for "background color".

These changes are on the `master` branch and should be tested on mobile and desktop browsers.

**Comment by sharonmleon** [comment]
Works as expected on Firefox, Safari, and Chrome for Mac.
