### ISSUE TITLE
Collecting form styling

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-themes/papers#11]
There might not be styles for collecting forms? This might be a problem across a bunch of themes.
![Screenshot 2021-07-22 at 13-24-56 Histories of the National Mall · Welcome · SML Omeka S Test](https://user-images.githubusercontent.com/741480/126682832-859424f9-d79b-40cf-b0df-41c21cbbf2a1.png)

**Comment by kimisgold** [comment]
@sharonmleon I've generalized the advanced search styles to apply to other forms using our `.field` markup, like Collecting. Can you pull and see if this looks better to you?

**Comment by sharonmleon** [comment]
Oddness. I got an extra bar above the admin bar and I lost my scroll. But the form looks nice, I think. Still, the input box for the title is not the same width as the input box for the prompt question.

![Screenshot 2021-07-27 at 11-43-09 Histories of the National Mall · Item Showcase · SML Omeka S Test](https://user-images.githubusercontent.com/741480/127184837-e2d49a61-5ee6-448a-9fcf-b6108428f12b.png)

**Comment by kimisgold** [comment]
Those are default widths for those inputs. We could set full width styles for Collecting form inputs within the module.

The interesting part of this screenshot is how the collecting form columns are all using center alignment. I'm not able to reproduce that on my own install.

**Comment by kimisgold** [comment]
Okay, so the weirdness was because this theme provides the url slug as a body class, and this url slug was `item-showcase`. I will do something about that as a separate issue. I'll also provide nicer default input styles within the Collecting module itself.
