### ISSUE TITLE
Browse preview styles?

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-themes/papers#13]
Page includes Page Title and Browse Preview blocks: http://6floors.org/workspace/omeka-s/s/mall/page/Images

Console: Loading failed for the <script> with source “http://6floors.org/workspace/omeka-s/themes/papers/asset/js/default.js?v=1.2.1”. Images:62:1

​
Printed Error:

Error: Function name must be a string in /home/sharonml/public_html/6floors.org/workspace/omeka-s/themes/papers/view/common/block-layout/browse-preview.phtml:29
Stack trace:
#0 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include()
#1 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
#2 [internal function]: Laminas\View\Helper\Partial->__invoke('common/block-la...', Array)
#3 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array)
#4 /home/sharonml/public_html/6floors.org/workspace/omeka-s/application/src/Site/BlockLayout/BrowsePreview.php(171): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
#5 /home/sharonml/public_html/6floors.org/workspace/omeka-s/application/src/View/Helper/BlockLayout.php(124): Omeka\Site\BlockLayout\BrowsePreview->render(Object(Laminas\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#6 /home/sharonml/public_html/6floors.org/workspace/omeka-s/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#7 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/home/sharonml/...')
#8 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#9 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#10 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#11 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#12 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#13 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#14 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#15 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#16 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#17 /home/sharonml/public_html/6floors.org/workspace/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#18 /home/sharonml/public_html/6floors.org/workspace/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#19 {main}

**Comment by kimisgold** [comment]
Wrote the escape html variable incorrectly, should be fixed now. Can you pull and confirm?

**Comment by sharonmleon** [comment]
Fixed!
