### ISSUE TITLE
Test configurable page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/papers#17]
This is the theme-specific issue for omeka/omeka-s#1859. Please test this using the latest version of Omeka S on the `develop` branch.

Papers now supports configurable resource page blocks. On a site's theme settings panel, select Papers's "Configure resource pages" button. Test that blocks can be reordered, removed, and readded on the show views of items, media, and item sets. Papers only has a single "Main" block region.

**Comment by katknow** [comment]
The Resource Class block isn't working in item sets on this one either, but the item and media configurations seem to be working correctly.

**Comment by kimisgold** [comment]
Got it, the item set fix should be ready to look at.

**Comment by katknow** [comment]
This is now working as expected.
