### ISSUE TITLE
Button borders

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/papers#19]
Line 250 of 
themes/papers/asset/css/style.css?v=1.4.0 

has a border-width override happening:
![papers](https://user-images.githubusercontent.com/28012148/211096892-e4f456e0-15cc-40a1-88fe-8b8902a01519.PNG)

> border-width: 3px 1px 1px;

which is making the buttons look very funny.

**Comment by kimisgold** [comment]
The form buttons have been pared back. Could you pull and give your impressions?

**Comment by allanaaa** [comment]
This is still appearing, and in some new places too I think (but not on every button):
![papers-buttons](https://user-images.githubusercontent.com/28012148/219759463-3520d94d-f4e9-4388-811c-8624d3d9cb10.PNG)
![papers-buttons2](https://user-images.githubusercontent.com/28012148/219759472-a15c8c18-d9ad-42fd-b622-522f5da729c1.PNG)
![papers-buttons3](https://user-images.githubusercontent.com/28012148/219759474-da44b1b1-8ee3-4fc8-ae0a-f5226e37f45f.PNG)

**Comment by kimisgold** [comment]
A lot of this was a style choice. I don't think it looks great on every button necessarily, but it's not a bug. My current feeling is that I like it on buttons with text labels and it doesn't look as good on those containing font icons. That kind of targeting is a little difficult, but I welcome further feedback on deciding upon consistent approaches to styling these form elements.
