### ISSUE TITLE
Test option to show search in header

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/papers#2]
[A forum poster noted that this theme doesn't show the search bar in the header by default](https://forum.omeka.org/t/default-search-for-papers-theme/10593/3), which was a byproduct of PWD opting to link to the advanced search instead of using an persistent search bar. I've added a theme option to toggle the search. I opted to keep the search off by default as to not disrupt any existing theme users who may have their sites disrupted by the sudden appearance of a new header element.

This issue needs to test the following on the `search-toggle` branch: 

* Search appears in header if theme setting checked
* Search form looks good at both mobile and desktop widths.

**Comment by mebrett** [comment]
### On Desktop

Content on the search results page doesn't have the same margin as regular page blocks, so search results are suddenly off to the left compared to regular content 

<img width="1355" alt="Screen Shot 2020-03-04 at 2 44 59 PM" src="https://user-images.githubusercontent.com/2314070/75916905-283c5700-5e27-11ea-99c5-ee1ff8d6d2b4.png">
<img width="520" alt="Screen Shot 2020-03-04 at 2 47 01 PM" src="https://user-images.githubusercontent.com/2314070/75916910-296d8400-5e27-11ea-916d-502dbe1758cf.png">

### On mobile
the text scales down to a point where search results might be too close together for fat-fingered clicking/mobility issues. The blue squares in the below image are the same size. 
![IMG_E6A911E9FE34-1](https://user-images.githubusercontent.com/2314070/75917449-02fc1880-5e28-11ea-8914-1d86a86462b0.jpeg)

**Comment by kimisgold** [comment]
Hopefully these are now addressed in 5e031b18c93f5918327fc59d39169312c2ca3c61, alongside nicer search result styles.

**Comment by kimisgold** [comment]
@mebrett Could you test that your previous comments have been addressed? Namely the centering issue as well as the larger touch targets for search results.

**Comment by mebrett** [comment]
Just checking that it's still `search-toggle` and not master?

**Comment by kimisgold** [comment]
Yup!

**Comment by mebrett** [comment]
Spacing on search results is better.
The search results page still aligns all the way to the left rather than matching the rest of the pages. I also noticed that on the browse item page, the content width cuts off the word "descending" on the sort/filter dropdown. 
<img width="885" alt="Screen Shot 2020-07-06 at 11 18 18 AM" src="https://user-images.githubusercontent.com/2314070/86609953-a7c76780-bf7a-11ea-9e54-04e278910a3c.png">

**Comment by kimisgold** [comment]
I realize the page alignment is because I was targeting markup introduced in Omeka S v3. That should be fixed in the `search-toggle` branch now (though nicer styles for the new search won't appear until v3 arrives). I've also increased the content's maximum width. I realize 900px was a little narrow, especially since default laptop resolutions skew wider these days.

**Comment by mebrett** [comment]
Looks good.
