### ISSUE TITLE
Font sizes on Advanced Search and Map Browse

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/papers#23]
![papersfontsizes](https://github.com/omeka-s-themes/papers/assets/28012148/3776bade-80ef-4f06-ae56-eb172e5af694)
![papersmapbrowse](https://github.com/omeka-s-themes/papers/assets/28012148/a1574f83-fb0c-493f-a116-b3aa4c4f700a)

The difference seems to be:
```
.field-meta .label {
  font-size: 22.5px;
}
```
is applying to `.label`s, but not labels. I suppose you could just make all labels `class="label"` in core/modules rather than fix the themes.

**Comment by zerocrates** [comment]
The question would be a little open as to whether the theme intends the big style at all or not: most labels are `label` elements and not `span.label`.

I don't think we want to have `label`s all need `.label` so we probably won't go that way around, but I think the question here is between just removing that style, or adding `label` to it. Removing it seems like maybe it's more the intended idea?

**Comment by kimisgold** [comment]
Fixed in https://github.com/omeka-s-themes/papers/commit/59fc07a20037567318d69475f5868e7542a66d2d.
