### ISSUE TITLE
Next and Previous buttons do not update with color changes

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/papers#6]
If a user configures the theme to change the colors, it does not change the colors for these buttons. 

Set a page as:
![Screen Shot 2020-12-17 at 2 29 16 PM](https://user-images.githubusercontent.com/2314070/102534135-4a305e80-4074-11eb-88f7-a3894c8a08ec.png)

But still seeing:
![Screen Shot 2020-12-17 at 2 29 05 PM](https://user-images.githubusercontent.com/2314070/102534150-4ef51280-4074-11eb-930b-277001a65f19.png)

**Comment by joebauer** [comment]
We're seeing the same thing.
